// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcbKj-nHAX1ZiEDpIF3Zx88rcCXd0nHj0',
    appId: '1:672645600243:web:15e746a63f0e10cbe2b886',
    messagingSenderId: '672645600243',
    projectId: 'pccehackathon-cd93b',
    authDomain: 'pccehackathon-cd93b.firebaseapp.com',
    storageBucket: 'pccehackathon-cd93b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbw_9q7Hd2JGEIoyf-LdnZ9Fiaqx51DVc',
    appId: '1:672645600243:android:b96594a6d0602b90e2b886',
    messagingSenderId: '672645600243',
    projectId: 'pccehackathon-cd93b',
    storageBucket: 'pccehackathon-cd93b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOzBqiSFDDglu59lUnkhygo_BDNmo7SlY',
    appId: '1:672645600243:ios:96b90145358efff1e2b886',
    messagingSenderId: '672645600243',
    projectId: 'pccehackathon-cd93b',
    storageBucket: 'pccehackathon-cd93b.firebasestorage.app',
    iosBundleId: 'com.example.hackathonpcce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOzBqiSFDDglu59lUnkhygo_BDNmo7SlY',
    appId: '1:672645600243:ios:96b90145358efff1e2b886',
    messagingSenderId: '672645600243',
    projectId: 'pccehackathon-cd93b',
    storageBucket: 'pccehackathon-cd93b.firebasestorage.app',
    iosBundleId: 'com.example.hackathonpcce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcbKj-nHAX1ZiEDpIF3Zx88rcCXd0nHj0',
    appId: '1:672645600243:web:fa61f8db3688347fe2b886',
    messagingSenderId: '672645600243',
    projectId: 'pccehackathon-cd93b',
    authDomain: 'pccehackathon-cd93b.firebaseapp.com',
    storageBucket: 'pccehackathon-cd93b.firebasestorage.app',
  );
}
