
import type { Transaction } from "@/components/dashboard/recent-transactions";
import { PlaceHolderImages } from "@/lib/placeholder-images";

export const initialTransactions: Transaction[] = [
    {
      id: '1',
      name: "Client A Payment",
      description: "Project Alpha",
      amount: 1999.00,
      type: "income",
      category: 'client-payment',
      paymentMethod: 'paypal',
      date: new Date('2023-10-25'),
      avatar: PlaceHolderImages.find(p => p.id === 'avatar-1'),
      client: { name: 'Client A' },
      status: 'paid',
    },
    {
      id: '2',
      name: "Software Subscription",
      description: "Design Tool for Project Alpha",
      amount: 49.00,
      type: "expense",
      category: 'software',
      paymentMethod: 'card',
      date: new Date('2023-10-24'),
      avatar: PlaceHolderImages.find(p => p.id === 'avatar-2'),
      client: { name: 'Client A' },
    },
    {
      id: '3',
      name: "Client B Payment",
      description: "Project Beta",
      amount: 3200.50,
      type: "income",
      category: 'client-payment',
      paymentMethod: 'bank',
      date: new Date('2023-10-22'),
      avatar: PlaceHolderImages.find(p => p.id === 'avatar-3'),
      client: { name: 'Client B' },
      status: 'paid',
    },
    {
      id: '4',
      name: "Office Supplies",
      description: "Stationery",
      amount: 120.00,
      type: "expense",
      category: 'office-supplies',
      paymentMethod: 'razorpay',
      date: new Date('2023-10-21'),
      avatar: PlaceHolderImages.find(p => p.id === 'avatar-4'),
    },
    {
      id: '5',
      name: "Client C Invoice",
      description: "Consulting",
      amount: 500.00,
      type: "income",
      category: 'client-payment',
      paymentMethod: 'gpay',
      date: new Date('2023-10-20'),
      avatar: PlaceHolderImages.find(p => p.id === 'avatar-1'),
      client: { name: 'Client C' },
      status: 'overdue',
      dueDate: new Date('2023-10-15'),
    },
    {
      id: '6',
      name: "Client B Marketing",
      description: "Ad spend for Project Beta",
      amount: 300.00,
      type: "expense",
      category: 'marketing',
      paymentMethod: 'card',
      date: new Date('2023-10-18'),
      client: { name: 'Client B' },
    },
     {
      id: '7',
      name: "Client D Invoice",
      description: "Web Development",
      amount: 2500.00,
      type: "income",
      category: 'client-payment',
      paymentMethod: 'bank',
      date: new Date('2023-11-01'),
      client: { name: 'Client D' },
      status: 'pending',
      dueDate: new Date('2023-11-15'),
    },
];
