import React from 'react';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    color: '#059669',
  },
  section: {
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    marginBottom: 10,
    color: '#374151',
  },
  subtitle: {
    fontSize: 14,
    marginBottom: 5,
    color: '#6B7280',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  label: {
    fontSize: 12,
    color: '#4B5563',
  },
  value: {
    fontSize: 12,
    color: '#111827',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    fontSize: 10,
    color: '#9CA3AF',
    textAlign: 'center',
  },
});

// Create Document Component
const SustainabilityReport = () => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>EcoConnect Sustainability Report</Text>
      
      {/* Key Metrics Section */}
      <View style={styles.section}>
        <Text style={styles.title}>Key Performance Metrics</Text>
        <View style={styles.row}>
          <Text style={styles.label}>QR Codes Scanned</Text>
          <Text style={styles.value}>2,847 (+12%)</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Active Users</Text>
          <Text style={styles.value}>1,234 (+8%)</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Items Recycled</Text>
          <Text style={styles.value}>5,692 (+15%)</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Environmental Score</Text>
          <Text style={styles.value}>94/100</Text>
        </View>
      </View>

      {/* Top Products Section */}
      <View style={styles.section}>
        <Text style={styles.title}>Top Performing Products</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Eco Water Bottle</Text>
          <Text style={styles.value}>456 scans</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Smart Phone Case</Text>
          <Text style={styles.value}>324 scans</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Food Container</Text>
          <Text style={styles.value}>289 scans</Text>
        </View>
      </View>

      {/* Environmental Impact Section */}
      <View style={styles.section}>
        <Text style={styles.title}>Environmental Impact</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Total CO₂ Saved</Text>
          <Text style={styles.value}>8.1 tons</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Total Items Recycled</Text>
          <Text style={styles.value}>5,470 items</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Recycling Rate</Text>
          <Text style={styles.value}>92%</Text>
        </View>
      </View>

      {/* Material Breakdown */}
      <View style={styles.section}>
        <Text style={styles.title}>Material Breakdown</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Plastic</Text>
          <Text style={styles.value}>2,340 kg (4.2 tons CO₂ saved)</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Electronics</Text>
          <Text style={styles.value}>890 kg (1.8 tons CO₂ saved)</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Glass</Text>
          <Text style={styles.value}>1,560 kg (0.9 tons CO₂ saved)</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Metal</Text>
          <Text style={styles.value}>680 kg (1.1 tons CO₂ saved)</Text>
        </View>
      </View>

      <Text style={styles.footer}>
        Generated by EcoConnect on {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);

export const PDFDownloadButton = () => (
  <PDFDownloadLink
    document={<SustainabilityReport />}
    fileName={`sustainability-report-${new Date().toISOString().split('T')[0]}.pdf`}
  >
    {({ loading }) => (
      <button 
        className={`bg-white text-green-600 px-6 py-3 rounded-lg font-medium transition-colors ${
          loading ? 'opacity-50 cursor-wait' : 'hover:bg-green-50'
        }`}
        disabled={loading}
      >
        {loading ? 'Preparing Report...' : 'Generate Report'}
      </button>
    )}
  </PDFDownloadLink>
);